### ISSUE TITLE
How to write definition for multi-line commands?

### ISSUE THREAD

**Issue by enarkay** [matyalatte/Simple-Command-Runner#14] opened 2023-06-13 18:46 UTC
I have been utilizing simple-command-runner to make simple & intuitive tools for so many of my repetitive jobs.
I just cannot thank you enough for this wonderful tool - you truly are a life savior.

However, while I've successfully managed to write up the required definition json files by thoroughly studying the example files and by a lot of trial-and-error, I just cannot figure out how to make the program carry out a multi-line command.

For example:

@echo off
color a
set /p folder="Enter the directory to search: "
set /p search="Enter the text to search: "
for %%a in ("%folder%\*.assets";"%folder%\level???";"%folder%\*.bundle") do UnityEX.exe search "%%a" -nr -sp "%search%" -lf search_output_mbnew.txt -mb_new
pause

I am trying to convert the above BAT file into another simple-command-runner, but all my attempts so far have unfortunately failed.
Could you be so kind as to instruct me how I can achieve my objective?

Or could it be that the simple-command-runner does not support commands that are carried out through multiple lines?

**Comment by matyalatte** [comment] 2023-06-13 22:01
The cause could be a bug that `%%` won't escape the `%` symbol.
Here is a fixed exe from the dev branch.
It should work with commands that have `%%`.
[SimpleCommandRunner.zip](https://github.com/matyalatte/Simple-Command-Runner/files/11739679/SimpleCommandRunner.zip)

It doesn't support multiple lines (cause it'll just run `cmd.exe` with an argument.)
But it should work if you join the lines into a single line with ` && `.

So, what you should do is...
- Use the fixed version.
- Join the lines with ` && `.
- Add `\` for escaping some symbols.
- Use [`id`](https://github.com/matyalatte/Simple-Command-Runner/tree/main/examples/comp_options/id) options to insert an input into multiple places.

For example, the following json will work to search `txt` and `json`.
```json
{
    "gui": [
        {
            "label": "Search txt and json in a folder",
            "command": "@echo off && for %%f in (\"%dir%\\*.txt\"; \"%dir%\\*.json\") do (echo %%f)",
            "button": "Echo!",
            "components": [
                {
                    "type": "folder",
                    "label": "a folder",
                    "id": "dir"
                }
            ]
        }
    ]
}
```

**Comment by matyalatte** [comment] 2023-06-13 22:11
And there is another workaround.
Batch files can get arguments with `%1`, `%2`, etc.
So, you can run a batch file via exe.
like this.
`"command": "foo.bat %folder% %search%"`

**Comment by enarkay** [comment] 2023-06-14 08:10
Thank you so much for such a fast reply to the issue.

Maybe it's just me, but despite your instructions and example I am constantly failing to make the program successfully run the desired command. I will give it a few more tens of tries, then ask you for help if I ultimately fail.

But in the meanwhile, I found a little typo in the error message :)
[LoadDefinition] Error: Fialed to load gui_definition.json

Fialed → Failed

**Comment by matyalatte** [comment] 2023-06-14 13:33
Well, you can see the error message to know why the json file is invalid.
If you get no errors, you can see the actual executed command on the black window, like `[RunCommand] Command: "The executed command"`.
If the command looks fine but it won't work as you expected, it's more general problem like "How can I run multiple commands as a single line on the command prompt?"

> Fialed → Failed

Thanks for the info.
I found 2 typos in docs too. Might be more.

**Comment by enarkay** [comment] 2023-06-14 15:28
Could you specify exactly which symbols I should be escaping with '\'?
And where exactly should I be putting them? Before or after the symbols I want to escape?

I am using the latest/dev version of SCR you provided, and while I've tried numerous times with all possible combinations by including and excluding the esacpe sign (\), I was not able to succeed in any one of them.


The last one I've tried at this point and the error message are as follows :


<<Command>>
@echo off && color a && for %%a in (\"%folder%\\*.assets\"; \"%folder%\\level???\"; \"%folder%\\*.bundle\") do UnityEX.exe search "%%a" -nr -sp \"%search%\" -lf "E:\Localization\Unity Tools Collection\UnityEX\search_BAT\search_output_mbnew.txt" -mb_new


<<Error Message>>
Simple Command Runner v0.4.0 by matyalatte
[LoadDefinition] Error: [json.exception.parse_error.101] parse error at line 5, column 150: syntax error while parsing object - invalid literal; last read: '"@echo off && color a && for %%a in (\"%folder%\\*.assets\"; \"%folder%\\level???\"; \"%folder%\\*.bundle\") do UnityEX.exe search "%'; expected '}'
[LoadDefinition] Loaded gui_definition.json
[LoadDefinition] Error: Fialed to load gui_definition.json (['command'] should be a string.)
[UpdatePanel] Default GUI

**Comment by matyalatte** [comment] 2023-06-14 15:56
`"` and `\` should be escaped by `\`.
I mean, `\"` will work as `"` in json. `\\` will work as `\`.

I recommend that you use a code editor (like VSCode, an online JSON editor, or something like that.)
They can tell you the syntax errors while editing files.
like this
![Screenshot (923)](https://github.com/matyalatte/Simple-Command-Runner/assets/69258547/22e58c9d-e233-441e-9ac1-f133ef22346b)

**Comment by matyalatte** [comment] 2023-06-15 15:21
Glad to hear that. I'll close this issue.

**Closed by matyalatte** 2023-06-15 15:21 UTC
